[package]
name = "hworld"
version = "0.1.0"
authors = ["lemon-mint <55233766+lemon-mint@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
